baseURL: https://galaxys-threads-hugo.appbyte.net
languageCode: en-us
title: Galaxy's Threads
theme: elementary
menus:
  main:
    - name: Aurebesh Mode
      url: https://chrome.google.com/webstore/detail/aurebesh-mode/hdhhdjnopmenaffkokpopaglihanddhh
      weight: 98
    - name: Shop
      url: https://etsy.com/shop/GalaxysThreads
      weight: 99
params:
  disclaimer: "Please Note: Galaxy's Threads fan-run organization and is NOT affiliated with Lucasfilm Ltd. or The Walt Disney Company."
  disableLightMode: true
